### ISSUE TITLE
Forces reload of association raising deprecation warning in Rails 5

### ISSUE THREAD

**Issue by samphilipd** [markets/unscoped_associations#16]
We pass the association name as an argument to `super` in `add_unscoped_association`. Rails interprets this as a 'truthy' value and forces a reload of the model. In Rails 5 this raises a deprecation warning:

```
DEPRECATION WARNING: Passing an argument to force an association to reload is now deprecated and will be removed in Rails 5.1. Please call `reload` on the parent object instead.
```

**Comment by markets** [comment]
Related to #14

**Comment by markets** [comment]
hi @samphilipd, I'm going to close this: https://github.com/markets/unscoped_associations/pull/14#issuecomment-270372659

Thanks!

**Comment by samphilipd** [comment]
@markets looks better with the caching but this actually doesn't fix it. This code will still break in rails 5, you might want to reopen the ticket

**Comment by samphilipd** [comment]
Sorry I meant to say rails 5.1

**Comment by markets** [comment]
Sorry @samphilipd, this gem isn't actually compatible with Rails 5.1: https://github.com/markets/unscoped_associations/blob/master/unscoped_associations.gemspec#L19:

> spec.add_dependency "activerecord", ">= 3.2.0", "<= 5.1.0"

From 5.1 some of the methods this gem use internally are deprecated, so I'm not planning to support > 5.1 right now.
