### ISSUE TITLE
Undefined method alias_method_chain

### ISSUE THREAD

**Issue by xbits** [markets/unscoped_associations#21]
Rails fails to load the gem and throws this error on startup. 
Versions:
- ruby 2.4.0p0
- Rails 5.1.2
- unscoped_associations (0.6.5)

```
.rvm/gems/ruby-2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'unscoped_associations'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
Did you mean?  alias_method
Backtrace for gem load error is:
/home/xbits/.rvm/gems/ruby-2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:7:in `block in included'
/home/xbits/.rvm/gems/ruby-2.4.0/gems/unscoped_associations-0.6.5/lib/unscoped_associations.rb:6:in `instance_eval'
```

**Comment by markets** [comment]
Hi @xbits, sorry this gem isn't actually compatible with Rails 5.1 as noted in the Readme:

> Officially supported (tested) Active Record versions: 3.2, 4.0, 4.1, 4.2 and 5.0.

And in the `gemspec`:

https://github.com/markets/unscoped_associations/blob/525593d4f3b45a759ff523744eea848f3d952d8d/unscoped_associations.gemspec#L18

Rails 5.0 was supported as a migration path to facilitate upgrades (you can read more info about current status [here](https://github.com/markets/unscoped_associations#status)). Also, you can take a look to the issue #19 for further explanations.

Maybe you can try a fork: https://github.com/markets/unscoped_associations/network. Seems that some of them are Rails 5.1+ compatible: [akeyhero/unscoped_associations](https://github.com/akeyhero/unscoped_associations), [djpate/unscoped_associations](https://github.com/djpate/unscoped_associations), [edwardmp/unscoped_associations](https://github.com/edwardmp/unscoped_associations/tree/fix-deprecated-alias-method-chain).

**Comment by xbits** [comment]
Hi @markets, sorry I missed that part of the readme. Thank you for the quick reply!
