### ISSUE TITLE
with #includes causes n + 1

### ISSUE THREAD

**Issue by calvinl** [markets/unscoped_associations#6]
When loading polymorphic association with `unscoped: true`, it breaks eager loading with `includes`.

**Comment by diophore** [comment]
I just discovered the same issue.

**Comment by markets** [comment]
Hi @diophore, sorry but it seems an issue related to `Rails` itself and how `unscoped` works. I think it was fixed in last releases. Let me check that (probably during this week) and I'll try to clarify the situation about this point. Thanks!

**Comment by diophore** [comment]
The app was on Rails 4.1.4.

**Comment by markets** [comment]
Hi @diophore, I just made a quick review and it's definitely not fully solved in Rails. Some related issues/commits:
https://github.com/rails/rails/issues/10643, https://github.com/rails/rails/issues/12405, https://github.com/rails/rails/issues/13775, https://github.com/rails/rails/issues/18983, https://github.com/rails/rails/commit/e8f223a4b43b8a3e95c3681ef7355cc963dbdcfe ... some of them are closed, but I can see recent comments with people having weird behaviours. Seems that unscope associations + eager load actually aren't playing well. I'll review it in-depth and see if we can apply some kind of workaround (or at least a note in the docs).

**Comment by markets** [comment]
Hi guys, I added some notes about this behavior in the Readme! If you found any solution just ping me o send a PR. Thanks!
